### ISSUE TITLE
Problema al obtener variables de la dashboard en neatbeans con la funcion getvalues

### ISSUE THREAD

**Issue by Sergiojaramillo** [ubidots/ubidots-java#10]
Value[] values;
        values = Temperatura.getValues();
        System.out.println(Arrays.toString(values));

Al usar estos valores en el código me aparece lo siguiente 

[com.ubidots.Value@708f5957, com.ubidots.Value@68999068, com.ubidots.Value@7722c3c3 ETC no puedo ver los valores de temperatura en consola, alguien me podría ayudar?? y si de pronto tienen el archivo actualizado con las depencencias y el pom. gracias. soy nuevo en java y la verdad es un poco complicado agregar bien las dependencias. si pude obtener valores estadísticos con la función double mean = Temperatura.getMean(); y en consola 30.966361315512838, pero no puedo ver los valores con getvalue. alguien que me pueda colaborar

**Comment by juanda95** [comment]
Hola, Sergio!

La salida que estás recibiendo es correcta para la declaración que haces en la linea:
```java
System.out.println(Arrays.toString(values))
```

Para obtener el valor normal de forma correcta puedes hacer lo siguiente:
```java
Value[] values = Temperatura.getValues();
for (Value value : values) {
    System.out.println(value.getValue());
}
```

Lo que ocurre es que estás mostrando la representación en String de la clase Value en lugar del valor que te devuelve el método `getValue()`.

**Comment by Sergiojaramillo** [comment]
Muchisimas gracias juanda95 excelente aporte ya muestra los valores muy bien te agradezco

**Comment by juanda95** [comment]
Genial que te funcione, Sergio.

En este caso daré el issue por cerrado, muchas gracias por preguntar :smile:
