### ISSUE TITLE
Problema al imprimir

### ISSUE THREAD

**Issue by Sergiojaramillo** [ubidots/ubidots-java#11]
Buenas noches 

Tengo problemas al imprimir en consola todos los datos de temperatura, solo imprime 50 valores y tengo muchos mas en la dashboard en ubidots 
Variable Temperatura = api.getVariable("57a3591e762542603827143d");
Value[] values = Temperatura.getValues();    
 for (Value value : values) {
        System.out.println(value.getValue());
        }
Este es el código. Como podría extraer mas datos???

**Comment by juanda95** [comment]
Hola Sergio, así es como actualmente funciona el paginado de la API con los parámetros por defecto te trae los 50 últimos valores de la variable que estés usando.
La librería de Java para Ubidots no tiene actualmente una forma de enviarle parámetros personalizados a la API. Se podría agregar esto como una característica deseada para la próxima revisión de la librería.

**Comment by Sergiojaramillo** [comment]
Hola juanda 95 ahh q mal. No hay una manera de extraer mas datos ??? Modificar algo para extraer mas ??

**Comment by juanda95** [comment]
Hola Sergio, te cuento. El día Viernes 19 de Agosto se hizo la actualización de la librería para soportar parámetros personalizados.

Puedes usar la función getValues y enviarle un mapa como argumento, el mapa enviaría el parámetro:valor.

Un ejemplo sencillo sería:
```java
Map<String, String> customParams = new HashMap<>();
customParams.put("page_size", String.valueOf(60));

Value[] values = variable.getValues(customParams);
```

Que te debería devolver un máximo de 60 valores en esa petición.

Saludos!
