### ISSUE TITLE
Imprimir fecha y tiempo 

### ISSUE THREAD

**Issue by Sergiojaramillo** [ubidots/ubidots-java#12]
estoy tratando de imprimir la fecha de una variable entrante de ubidots, mi segmento de código es 
 System.out.println(values[1].getTimestamp());
trato de imprimir la  hora y fecha de values y aparece 
1470507507917

Como puedo interpretar esto ???, es la manera correcta de usar la función?, o esta funcionalidad no la tiene la librería ?? 
Gracias

**Comment by juanda95** [comment]
Hola Sergio,
Efectivamente es la forma correcta de usar la función. Esta función está devolviendo un Unix epoch timestamp. Si deseas imprimir la fecha en un formato "Human Readable" (e.g. DD/MM/AAAA) deberías hacer uso de alguna librería que te permita convertir desde un Unix Epoch Timestamp, como por ejemplo java.util.Date.

**Comment by Sergiojaramillo** [comment]
Gracias juanda muy amable por tu ayuda me queda muy claro todo 
El 17/08/2016 8:33 a.m., David Sánchez <notifications@github.com> escribió:Hola Sergio,
Efectivamente es la forma correcta de usar la función. Esta función está devolviendo un Unix epoch timestamp. Si deseas imprimir la fecha en un formato "Human Readable" (e.g. DD/MM/AAAA) deberías hacer uso de alguna librería que te permita convertir desde un Unix Epoch Timestamp, como por ejemplo java.util.Date.

**Comment by woakas** [comment]
@Sergiojaramillo hay una forma que puedes usar que es la siguiente:

```
String date = new java.text.SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(new java.util.Date (values[1].getTimestamp()));
```

y existen otras formas:
* http://stackoverflow.com/questions/2318719/how-to-convert-timestamp-string-to-java-util-date
* http://stackoverflow.com/questions/11839246/how-to-convert-timestamp-to-date-in-java
